-- CREATE TABLE `REVIEWS` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `user_id` INTEGER, `date` TEXT NOT NULL, `game` TEXT NOT NULL, `review` TEXT NOT NULL)
-- CREATE TABLE USERS (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT NOT NULL, password TEXT NOT NULL)
-- CREATE TABLE GAMES (id INTEGER PRIMARY KEY AUTOINCREMENT, game_id INTEGER NOT NULL, Title TEXT NOT NULL, Genre TEXT NOT NULL)
SELECT 
    REVIEWS.review_text, 
    REVIEWS.is_recommended, 
    GAMES.title 
FROM REVIEWS
JOIN GAMES ON REVIEWS.game_id = GAMES.id
WHERE REVIEWS.game_id = 1;